from .order_tools import ORDER_TOOL_DEFS, ORDER_EXECUTORS
from .customer_tools import CUSTOMER_TOOL_DEFS, CUSTOMER_EXECUTORS
from .product_tools import PRODUCT_TOOL_DEFS, PRODUCT_EXECUTORS
from .inventory_tools import INVENTORY_TOOL_DEFS, INVENTORY_EXECUTORS
from .fulfillment_tools import FULFILLMENT_TOOL_DEFS, FULFILLMENT_EXECUTORS
from .transaction_tools import TRANSACTION_TOOL_DEFS, TRANSACTION_EXECUTORS
from .draft_order_tools import DRAFT_ORDER_TOOL_DEFS, DRAFT_ORDER_EXECUTORS

SHOPIFY_TOOL_DEFS = (
    ORDER_TOOL_DEFS
    + CUSTOMER_TOOL_DEFS
    + PRODUCT_TOOL_DEFS
    + INVENTORY_TOOL_DEFS
    + FULFILLMENT_TOOL_DEFS
    + TRANSACTION_TOOL_DEFS
    + DRAFT_ORDER_TOOL_DEFS
)

TOOL_EXECUTORS = {
    **ORDER_EXECUTORS,
    **CUSTOMER_EXECUTORS,
    **PRODUCT_EXECUTORS,
    **INVENTORY_EXECUTORS,
    **FULFILLMENT_EXECUTORS,
    **TRANSACTION_EXECUTORS,
    **DRAFT_ORDER_EXECUTORS,
}
